# Use root/example as user/password credentials
name: 'mongo'
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
     - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: passw0rd
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: passw0rd
      ME_CONFIG_MONGODB_URL: mongodb://admin:passw0rd@mongo:27017/
      ME_CONFIG_BASICAUTH: false

#docker compose up -d 
#docker compose down 